export const categoryKeywords = {
  '技术': ['computer', 'software', 'hardware', 'technology', 'programming', 'code', 'system', 'network', 'data', 'digital'],
  '商业': ['business', 'company', 'market', 'finance', 'money', 'investment', 'trade', 'commerce', 'industry', 'enterprise'],
  '体育': ['sports', 'game', 'team', 'player', 'competition', 'athlete', 'match', 'tournament', 'championship', 'coach'],
  '政治': ['politics', 'government', 'election', 'policy', 'democracy', 'vote', 'campaign', 'party', 'leader', 'policy'],
  '科学': ['science', 'research', 'experiment', 'discovery', 'study', 'theory', 'scientist', 'laboratory', 'analysis', 'method']
};

export const translations: { [key: string]: { zh: string; en: string } } = {
  'NLP 文本分析工具': { zh: 'NLP 文本分析工具', en: 'NLP Text Analysis Tool' },
  '输入文本': { zh: '输入文本', en: 'Input Text' },
  '请输入要分析的文本...': { zh: '请输入要分析的文本...', en: 'Please enter text to analyze...' },
  '分析文本': { zh: '分析文本', en: 'Analyze Text' },
  '基础统计': { zh: '基础统计', en: 'Basic Statistics' },
  '字符数': { zh: '字符数', en: 'Character Count' },
  '词数': { zh: '词数', en: 'Word Count' },
  '句子数': { zh: '句子数', en: 'Sentence Count' },
  '检测到的语言': { zh: '检测到的语言', en: 'Detected Language' },
  '情感分析': { zh: '情感分析', en: 'Sentiment Analysis' },
  '情感倾向': { zh: '情感倾向', en: 'Sentiment' },
  '情感得分': { zh: '情感得分', en: 'Sentiment Score' },
  '实体识别': { zh: '实体识别', en: 'Entity Recognition' },
  '词性分析': { zh: '词性分析', en: 'Part of Speech Analysis' },
  '动词': { zh: '动词', en: 'Verbs' },
  '形容词': { zh: '形容词', en: 'Adjectives' },
  '名词': { zh: '名词', en: 'Nouns' },
  '关键词': { zh: '关键词', en: 'Keywords' },
  '文本分类': { zh: '文本分类', en: 'Text Classification' },
  '文本相似度': { zh: '文本相似度', en: 'Text Similarity' },
  '比较文本': { zh: '比较文本', en: 'Compare Text' },
  '请输入要比较的文本...': { zh: '请输入要比较的文本...', en: 'Please enter text to compare...' },
  '相似度': { zh: '相似度', en: 'Similarity' },
  '文本摘要': { zh: '文本摘要', en: 'Text Summary' },
  '句子列表': { zh: '句子列表', en: 'Sentence List' },
  '分析结果 JSON': { zh: '分析结果 JSON', en: 'Analysis Results JSON' },
  '复制到剪贴板': { zh: '复制到剪贴板', en: 'Copy to Clipboard' },
  '人物': { zh: '人物', en: 'Person' },
  '地点': { zh: '地点', en: 'Location' },
  '组织': { zh: '组织', en: 'Organization' },
  '非常积极': { zh: '非常积极', en: 'Very Positive' },
  '积极': { zh: '积极', en: 'Positive' },
  '中性': { zh: '中性', en: 'Neutral' },
  '消极': { zh: '消极', en: 'Negative' },
  '非常消极': { zh: '非常消极', en: 'Very Negative' },
  '未知语言': { zh: '未知语言', en: 'Unknown Language' },
  '选择语言': { zh: '选择语言', en: 'Select Language' },
  '段落数': { zh: '段落数', en: 'Paragraphs' },
  '唯一词数': { zh: '唯一词数', en: 'Unique Words' },
  '平均词长': { zh: '平均词长', en: 'Average Word Length' },
  '平均句长': { zh: '平均句长', en: 'Average Sentence Length' },
  '阅读时间': { zh: '阅读时间', en: 'Reading Time' },
  '最常见词': { zh: '最常见词', en: 'Most Common Words' },
  '文本格式化': { zh: '文本格式化', en: 'Text Formatting' },
  '大写': { zh: '大写', en: 'UPPERCASE' },
  '小写': { zh: '小写', en: 'lowercase' },
  '首字母大写': { zh: '首字母大写', en: 'Title Case' },
  '句子格式': { zh: '句子格式', en: 'Sentence Case' },
  '导出文本': { zh: '导出文本', en: 'Export Text' },
  '导出为': { zh: '导出为', en: 'Export as' },
  '导出成功': { zh: '导出成功', en: 'Export successful' },
  '导出失败': { zh: '导出失败', en: 'Export failed' },
  '分钟': { zh: '分钟', en: 'minutes' },
  '字符': { zh: '字符', en: 'characters' },
  '文本聚类': { zh: '文本聚类', en: 'Text Clustering' },
  '添加文本': { zh: '添加文本', en: 'Add Text' },
  '删除文本': { zh: '删除文本', en: 'Remove Text' },
  '聚类结果': { zh: '聚类结果', en: 'Clustering Results' },
  '文本纠错': { zh: '文本纠错', en: 'Text Correction' },
  '原始文本': { zh: '原始文本', en: 'Original Text' },
  '修正建议': { zh: '修正建议', en: 'Correction Suggestions' },
  '应用修正': { zh: '应用修正', en: 'Apply Correction' },
  '摘要长度': { zh: '摘要长度', en: 'Summary Length' },
  '短': { zh: '短', en: 'Short' },
  '中': { zh: '中', en: 'Medium' },
  '长': { zh: '长', en: 'Long' },
  '检查文本': { zh: '检查文本', en: 'Check Text' },
  '已添加的文本': { zh: '已添加的文本', en: 'Added Texts' },
  '聚类': { zh: '聚类', en: 'Cluster' },
  '未发现错误': { zh: '未发现错误', en: 'No errors found' }
};

export const commonMistakes: { [key: string]: string[] } = {
  'teh': ['the'],
  'recieve': ['receive'],
  'seperate': ['separate'],
  'accomodate': ['accommodate'],
  'occured': ['occurred'],
  'alot': ['a lot'],
  'definately': ['definitely'],
  'existance': ['existence'],
  'independant': ['independent'],
  'persistant': ['persistent'],
  'refered': ['referred'],
  'truely': ['truly'],
  'untill': ['until'],
  'wierd': ['weird'],
  'writting': ['writing'],
  // ... 其他拼写错误
}; 